name: Node CI
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14, 16]
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Clone repository
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: npm install, build, and test
      run: npm install && npm test
